
## Load & Wrangle Survey Demographic Data
```{r warning = FALSE}
bgd_file <- file.path(here("..","data","adapt_observ_survey_responses", "Observatory_Bangladesh_2024_04_15.csv"))
  
ind_file <- file.path(here("..","data","adapt_observ_survey_responses", "Observatory_India_2024_04_15.csv"))

bgd_responses <- read_csv(bgd_file, show_col_types = FALSE)
  
ind_responses <-read_csv(ind_file, show_col_types = FALSE)


bgd_demos <- bgd_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))
 

ind_demos <- ind_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))
```


# Bangladesh
```{r bgd_summary}
# Select the index columns from your data
index_columns <- c("region", "gender", "age", "flood_year", "housing_damage", "property_loss", 
                   "contact_authority", "flood_close", "stay_residence", "flood_prepared", 
                   "housing_safe", "enough_eat", "move_rural_urban", "demo_income", 
                   "climate_problem", "trust_government")

# Initialize an empty list to store the summaries
bgd_summary_list <- list()

# Iterate over each index column
for (column in index_columns) {
  # Group the data by the index column and summarize the counts of each response type
  summary <- bgd_demos %>%
    group_by(!!sym(column)) %>%
    summarise(
      Yes = sum(. == "Yes" | . == "yes"),
      No = sum(. == "No" | . == "no"),
      `Not Disclosed` = sum(is.na(.) | . == "Not Disclosed"),
      Total = n()  # Total count of responses in the group
    ) %>%
    ungroup() %>%
    # Normalize the counts to proportions
    mutate(
      Yes = Yes / Total,
      No = No / Total,
      `Not Disclosed` = `Not Disclosed` / Total
    ) %>%
    dplyr::select(-Total)  # Remove the Total column after normalization
  
  # Store the summary in the list
  bgd_summary_list[[column]] <- summary
}

# Access the normalized summaries for each index column
bgd_summary_list
```
# India
# Bangladesh
```{r ind_summary}
# Select the index columns from your data
index_columns <- c("region", "gender", "age", "flood_year", "housing_damage", "property_loss", 
                   "contact_authority", "flood_close", "stay_residence", "flood_prepared", 
                   "housing_safe", "enough_eat", "move_rural_urban", "demo_income", 
                   "climate_problem", "trust_government")

# Initialize an empty list to store the summaries
ind_summary_list <- list()

# Iterate over each index column
for (column in index_columns) {
  # Group the data by the index column and summarize the counts of each response type
  summary <- bgd_demos %>%
    group_by(!!sym(column)) %>%
    summarise(
      Yes = sum(. == "Yes" | . == "yes"),
      No = sum(. == "No" | . == "no"),
      `Not Disclosed` = sum(is.na(.) | . == "Not Disclosed"),
      Total = n()  # Total count of responses in the group
    ) %>%
    ungroup() %>%
    # Normalize the counts to proportions
    mutate(
      Yes = Yes / Total,
      No = No / Total,
      `Not Disclosed` = `Not Disclosed` / Total
    ) %>%
    dplyr::select(-Total)  # Remove the Total column after normalization
  
  # Store the summary in the list
  ind_summary_list[[column]] <- summary
}

# Access the normalized summaries for each index column
ind_summary_list
```