---
author: "Sofia Ingersoll"
title: "Adaptation Observatory: Survey Response Demographics (Bangladesh & India)"
date: 2024-4-14
format:
  html:
    code-fold: true
    code-summary: "Show the code"
#embed-resources: true
---

## Set Up

```{r message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

#..........................load packages.........................
library(tidyverse)        # load the tidyverse package to assist with data wrangling & cleaning 

library(patchwork)        # load the patchwork package to assist in plot composition (displaying multiple data visualizations) 

library(showtext)         # load the showtext to more easily use fonts
library(here)

library(leaflet)
library(osmextract) 
library(units)
library(sf)
library(sfheaders)
library(sp)
library(raster)
library(tmap)
library(terra)
library(stars)
library(ggtext)
library(units)
```


## Load Data
```{r}
bgd_responses <- read_csv(here("..","data","adapt_observ_survey_responses", "Observatory_Bangladesh_2024_04_11.csv"), show_col_types = FALSE)
  
ind_responses <-read_csv(here("..","data","adapt_observ_survey_responses", "Observatory_India_2024_04_11.csv"), show_col_types = FALSE)
```


## Wrangle Data
```{r}
#head(bgd_responses)
#str(bgd_responses)
# to create a list of variables to subset
#colnames(bgd_responses)

# to get an idea of how many unique observations we have
# the length is 3515, therefore our dataset of 4698 contains repeating observations
# we'll use IPAddress to isolate unique participants 
# it's safe to double check these entrees with the age + gender columns to make sure multiple family members that are logging in from the same IPAddress aren't missed
length(unique(bgd_responses$IPAddress))
length(unique(bgd_responses$age))
length(unique(bgd_responses$gender))
length(unique(bgd_responses$region))
```


```{r}
# these lines are grouped by demographics of interest
  # top line relates to personal demographics
bgd_demos <- bgd_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  janitor::clean_names() %>%
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude))
 
         
# remove first two rows
bgd_demos <- bgd_demos[-c(1,2), ]

#bgd_demos
```

```{r}
# these lines are grouped by demographics of interest
  # top line relates to personal demographics
ind_demos <- ind_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  janitor::clean_names() %>%
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude))
 
         
# remove first two rows
ind_demos <- ind_demos[-c(1,2), ]


#ind_demos
```

## Analysis

#### BGD
```{r fig.height=12, fig.width=18}
colors <- c('#fb8500', '#219ebc','#023047')
# Define the title text with HTML tags
bar_title <- "Survey Response <span style='color:#fb8500;'>**Female**</span> & <span style='color:#219ebc;'>**Male**</span> Age Demographics"

bar_subtitle <- "The 2035 Initiative Adaptation Observatory: Bangladesh, 2024 April 11"


# Plotting
bgd_demos %>% 
  ggplot(aes(fill = gender)) +
  
  geom_bar(aes(x = age), position = "dodge", width = 1) +
  
  geom_text(stat = "count",
            aes(x = age,
                y = ..count..,
                label = ..count..),
            position = position_dodge(width = 1),
            vjust = 0.5,
            hjust = 1.5,
            size = 8,
            color = "grey2") +  # Adjust text position and appearance
  
  labs(title = bar_title,
       subtitle = bar_subtitle, 
       x = "Age",
       y = "Count") +
  
  scale_fill_manual(values = colors) +  # Set custom colors
  
  theme_classic() +
  
  theme(
    
    plot.title = element_markdown(size = 38,
                                  hjust = 0.5),
    
    plot.subtitle = element_markdown(size = 30,
                                     hjust = 0.5),
    
     # Increase facet wrap title size
    strip.text = element_text(size = 20),
    
    axis.title.x = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.title.y = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.text.x = element_text(size = 18),
    
    axis.text.y = element_text(size = 18),
    
    
    legend.position = "none",
   # space on the side of the plot
    #plot.margin = margin(t = 1, r = 1, b = 1, l = 1, "cm")
   
    plot.margin = unit(c(t = 1,
                         r = 2,
                         b = 1,
                         l = 1),
                       "cm")
    
  ) +
  
  scale_y_continuous(breaks = seq(0, 3000, by = 50)) +  # Increase y-axis tick marks
  
  coord_flip() 

# Plotting
bgd_demos %>% 
  ggplot(aes(fill = gender)) +
  
  geom_bar(aes(x = age), position = "dodge", width = 1) +
  
  geom_text(stat = "count",
            aes(x = age,
                y = ..count..,
                label = ..count..),
            position = position_dodge(width = 1),
            vjust = 0.5,
            hjust = -0.5,
            size = 8,
            color = "grey2") +  # Adjust text position and appearance
  
  labs(title = bar_title,
       subtitle = bar_subtitle, 
       x = "Age",
       y = "Count") +
  
  scale_fill_manual(values = colors) +  # Set custom colors
  
  theme_bw() +
  
  theme(
    
    plot.title = element_markdown(size = 38,
                                  hjust = 0.5),
    
    plot.subtitle = element_markdown(size = 30,
                                     hjust = 0.5),
    
     # Increase facet wrap title size
    strip.text = element_text(size = 20),
    
    axis.title.x = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.title.y = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.text.x = element_text(size = 18),
    
    axis.text.y = element_text(size = 18),
    
    
    legend.position = "none",
   # space on the side of the plot
    #plot.margin = margin(t = 1, r = 1, b = 1, l = 1, "cm")
   
    plot.margin = unit(c(t = 1,
                         r = 2,
                         b = 1,
                         l = 1),
                       "cm")
    
  ) +
  
  scale_y_continuous(breaks = seq(0, 300, by = 50)) +  # Increase y-axis tick marks
  
  coord_flip() + # Flip coordinates
  
  facet_wrap(~region)
```


#### IND
```{r fig.height=12, fig.width=18}
#fig.height=20, fig.width=28
# Define the title text with HTML tags
bar_title <- "Survey Response <span style='color:#fb8500;'>**Female**</span> & <span style='color:#219ebc;'>**Male**</span> Age Demographics"

bar_subtitle <- "The 2035 Initiative Adaptation Observatory: India, 2024 April 11"


# Plotting
ind_demos %>% 
  ggplot(aes(fill = gender)) +
  
  geom_bar(aes(x = age), position = "dodge", width = 1) +
  
  geom_text(stat = "count",
            aes(x = age,
                y = ..count..,
                label = ..count..),
            position = position_dodge(width = 1),
            vjust = 0.5,
            hjust = 2.5,
            size = 8,
            color = "grey2") +  # Adjust text position and appearance
  
  labs(title = bar_title,
       subtitle = bar_subtitle, 
       x = "Age",
       y = "Count") +
  
  scale_fill_manual(values = colors) +  # Set custom colors
  
  theme_classic() +
  
  theme(
    
    plot.title = element_markdown(size = 38,
                                  hjust = 0.5),
    
    plot.subtitle = element_markdown(size = 30,
                                     hjust = 0.5),
    
     # Increase facet wrap title size
    strip.text = element_text(size = 20),
    
    axis.title.x = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.title.y = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.text.x = element_text(size = 18),
    
    axis.text.y = element_text(size = 18),
    
    
    legend.position = "none",
   # space on the side of the plot
    #plot.margin = margin(t = 1, r = 1, b = 1, l = 1, "cm")
   
    plot.margin = unit(c(t = 1,
                         r = 2,
                         b = 1,
                         l = 1),
                       "cm")
    
  ) +
  
  scale_y_continuous(breaks = seq(0, 3000, by = 50)) +  # Increase y-axis tick marks
  
  coord_flip() 

# Plotting
ind_demos %>% 
  ggplot(aes(fill = gender)) +
  
  geom_bar(aes(x = age), position = "dodge", width = 1) +
  
  geom_text(stat = "count",
            aes(x = age,
                y = ..count..,
                label = ..count..),
            position = position_dodge(width = 1),
            vjust = 0.5,
            hjust = -0.5,
            size = 8,
            color = "grey2") +  # Adjust text position and appearance
  
  labs(title = bar_title,
       subtitle = bar_subtitle, 
       x = "Age",
       y = "Count") +
  
  scale_fill_manual(values = colors) +  # Set custom colors
  
  theme_bw() +
  
  theme(
    
    plot.title = element_markdown(size = 38,
                                  hjust = 0.5),
    
    plot.subtitle = element_markdown(size = 30,
                                     hjust = 0.5),
    
     # Increase facet wrap title size
    strip.text = element_text(size = 20),
    
    axis.title.x = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.title.y = element_text(size = 26,
                                angle = 0,
                                vjust = 0.5),
    
    axis.text.x = element_text(size = 18),
    
    axis.text.y = element_text(size = 18),
    
    
    legend.position = "none",
   # space on the side of the plot
    #plot.margin = margin(t = 1, r = 1, b = 1, l = 1, "cm")
   
    plot.margin = unit(c(t = 1,
                         r = 2,
                         b = 1,
                         l = 1),
                       "cm")
    
  ) +
  
  scale_y_continuous(breaks = seq(0, 300, by = 50)) +  # Increase y-axis tick marks
  
  coord_flip() + # Flip coordinates
  
  facet_wrap(~region)
```

### Density Distribution of Gender based on Age & Colored by Region (facet wrap by Gender)

also Age vs Demo_Age colored by gender

Werk in progress

## Geospatial Analysis
```{r include = TRUE}
ind_demo_sf <- ind_demos %>% 
  
  st_as_sf(coords = c("location_longitude", "location_latitude"), crs = 4326)
  
  
tmap_mode('view')

ind_response_map <- tm_shape(ind_demo_sf) +
  tm_basemap(leaflet::providers$Esri.WorldImagery) +
  tm_bubbles(alpha = 0.2,
             fill = 'ip_address',
             col = 'skyblue',) +
  tm_scalebar(position = c('left', 'bottom')) +
  tm_title("Adaptation Observatory Responses, Bangladesh (2024-4-11)")

ind_response_map
```


```{r include = TRUE}
bgd_demo_sf <- bgd_demos %>% 
  
  st_as_sf(coords = c("location_longitude", "location_latitude"), crs = 4326)
  
  
tmap_mode('view')

bgd_response_map <- tm_shape(bgd_demo_sf) +
  tm_basemap(leaflet::providers$Esri.WorldImagery) +
  tm_bubbles(alpha = 0.2,
             fill = 'ip_address',
             col = 'skyblue',) +
  tm_scalebar(position = c('left', 'bottom')) +
  tm_title("Adaptation Observatory Responses, Bangladesh (2024-4-11)")

bgd_response_map
```

