% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{report}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={bgd\_data},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{bgd\_data}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2024-04-21 19:01:10.561915}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\chapter{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3472}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Number of observations & 3725 \\
Number of variables & 59 \\
\end{longtable}

\hypertarget{checks-performed}{%
\subsection{Checks performed}\label{checks-performed}}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.3649}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0811}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1149}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0676}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
character
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
haven labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
numeric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
integer
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
logical
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Date
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Identify miscoded missing values & \(\times\) & \(\times\) & \(\times\)
& \(\times\) & \(\times\) & \(\times\) & & \(\times\) \\
Identify prefixed and suffixed whitespace & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify levels with \textless{} 6 obs. & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify case issues & \(\times\) & \(\times\) & \(\times\) & \(\times\)
& & & & \\
Identify misclassified numeric or integer variables & \(\times\) &
\(\times\) & \(\times\) & \(\times\) & & & & \\
Identify outliers & & & & & \(\times\) & \(\times\) & & \(\times\) \\
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\hypertarget{summary-table}{%
\chapter{Summary table}\label{summary-table}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.3148}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1574}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2130}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1481}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Variable class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\# unique values
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Missing observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Any problems?
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\protect\hyperlink{start_date}{start\_date} & character & 3709 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{end_date}{end\_date} & character & 3704 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{status}{status} & character & 1 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{ip_address}{ip\_address} & character & 2904 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{progress}{progress} & character & 14 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{duration_in_seconds}{duration\_in\_seconds} &
character & 923 & 0.00 \% & \(\times\) \\
\protect\hyperlink{finished}{finished} & character & 2 & 0.00 \% & \\
\protect\hyperlink{recorded_date}{recorded\_date} & character & 3711 &
0.00 \% & \(\times\) \\
\protect\hyperlink{response_id}{response\_id} & character & 3725 & 0.00
\% & \(\times\) \\
\protect\hyperlink{recipient_last_name}{recipient\_last\_name} &
character & 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{recipient_first_name}{recipient\_first\_name} &
character & 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{recipient_email}{recipient\_email} & character & 1 &
100.00 \% & \(\times\) \\
\protect\hyperlink{external_reference}{external\_reference} & character
& 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{location_latitude}{location\_latitude} & numeric &
135 & 28.83 \% & \(\times\) \\
\protect\hyperlink{location_longitude}{location\_longitude} & numeric &
134 & 28.83 \% & \(\times\) \\
\protect\hyperlink{distribution_channel}{distribution\_channel} &
character & 1 & 0.00 \% & \(\times\) \\
\protect\hyperlink{user_language}{user\_language} & character & 2 & 0.00
\% & \\
\protect\hyperlink{meta_info_browser}{meta\_info\_browser} & character &
10 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_version}{meta\_info\_version} & character &
125 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_operating_system}{meta\_info\_operating\_system}
& character & 24 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_resolution}{meta\_info\_resolution} &
character & 226 & 0.00 \% & \(\times\) \\
\protect\hyperlink{consent_agreed}{consent\_agreed} & character & 1 &
0.00 \% & \(\times\) \\
\protect\hyperlink{consent_age}{consent\_age} & character & 1 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{consent_cellphone}{consent\_cellphone} & character &
1 & 0.00 \% & \(\times\) \\
\protect\hyperlink{gps_permission}{gps\_permission} & character & 3 &
2.23 \% & \\
\protect\hyperlink{household_move}{household\_move} & character & 3 &
13.88 \% & \\
\protect\hyperlink{flood_year}{flood\_year} & character & 3 & 15.22 \%
& \\
\protect\hyperlink{property_loss}{property\_loss} & character & 3 &
70.44 \% & \\
\protect\hyperlink{housing_damage}{housing\_damage} & character & 3 &
70.71 \% & \\
\protect\hyperlink{stay_residence}{stay\_residence} & character & 3 &
70.55 \% & \\
\protect\hyperlink{flood_close}{flood\_close} & character & 3 & 46.31 \%
& \\
\protect\hyperlink{flood_prepared}{flood\_prepared} & character & 6 &
23.06 \% & \\
\protect\hyperlink{housing_safe}{housing\_safe} & character & 6 & 23.62
\% & \\
\protect\hyperlink{climate_problem}{climate\_problem} & character & 6 &
23.79 \% & \\
\protect\hyperlink{trust_government}{trust\_government} & character & 6
& 23.30 \% & \\
\protect\hyperlink{enough_eat}{enough\_eat} & character & 3 & 22.82 \%
& \\
\protect\hyperlink{move_rural_urban}{move\_rural\_urban} & character & 3
& 23.38 \% & \\
\protect\hyperlink{contact_authority}{contact\_authority} & character &
3 & 23.97 \% & \\
\protect\hyperlink{demo_gender}{demo\_gender} & character & 4 & 25.15 \%
& \\
\protect\hyperlink{demo_age}{demo\_age} & character & 233 & 25.77 \% &
\(\times\) \\
\protect\hyperlink{demo_income}{demo\_income} & character & 678 & 26.90
\% & \(\times\) \\
\protect\hyperlink{comp_phone1_try1}{comp\_phone1\_try1} & character &
2382 & 33.05 \% & \(\times\) \\
\protect\hyperlink{comp_phone1_try2}{comp\_phone1\_try2} & character &
2353 & 33.96 \% & \(\times\) \\
\protect\hyperlink{comp_phone2_try1}{comp\_phone2\_try1} & character &
168 & 95.46 \% & \(\times\) \\
\protect\hyperlink{comp_phone2_try2}{comp\_phone2\_try2} & character &
160 & 95.73 \% & \(\times\) \\
\protect\hyperlink{comp_phone3_try1}{comp\_phone3\_try1} & character &
23 & 99.38 \% & \(\times\) \\
\protect\hyperlink{comp_phone3_try2}{comp\_phone3\_try2} & character &
24 & 99.36 \% & \(\times\) \\
\protect\hyperlink{geo_lat}{geo\_lat} & character & 1159 & 68.03 \% &
\(\times\) \\
\protect\hyperlink{geo_lng}{geo\_lng} & character & 1159 & 68.03 \% &
\(\times\) \\
\protect\hyperlink{q_url}{q\_url} & character & 3516 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{q_language}{q\_language} & character & 2 & 0.00 \%
& \\
\protect\hyperlink{gender}{gender} & character & 3 & 3.14 \% & \\
\protect\hyperlink{region}{region} & character & 11 & 3.14 \% & \\
\protect\hyperlink{age}{age} & character & 4 & 3.14 \% & \\
\protect\hyperlink{geo_capability}{geo\_capability} & character & 1 &
100.00 \% & \(\times\) \\
\protect\hyperlink{geo_status}{geo\_status} & character & 4 & 15.92 \%
& \\
\protect\hyperlink{geo_error}{geo\_error} & character & 2 & 56.64 \% &
\(\times\) \\
\protect\hyperlink{country}{country} & character & 1 & 100.00 \% &
\(\times\) \\
\protect\hyperlink{no_surverys_submitted}{no\_surverys\_submitted} &
integer & 12 & 0.00 \% & \\
\end{longtable}

\hypertarget{variable-list}{%
\chapter{Variable list}\label{variable-list}}

\hypertarget{start_date}{%
\section{start\_date}\label{start_date}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3709 \\
Mode & ``2024-03-25 21:10:23'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-1-start-date-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "2024-03-18 14:15:48", "2024-03-25 12:57:40", "2024-03-25 20:23:58",
  "2024-03-25 20:26:10", "2024-03-25 20:26:52", \ldots, "2024-04-05
  12:36:01", "2024-04-05 12:36:04", "2024-04-05 16:35:39", "2024-04-05
  18:06:17", "2024-04-09 10:26:44" (3699 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{end_date}{%
\section{end\_date}\label{end_date}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3704 \\
Mode & ``2024-03-25 21:31:08'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-2-end-date-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "2024-03-18 14:16:54", "2024-03-25 20:30:24", "2024-03-25 20:30:54",
  "2024-03-25 20:36:21", "2024-03-25 20:36:34", \ldots, "2024-04-05
  12:40:05", "2024-04-05 12:41:03", "2024-04-05 16:37:57", "2024-04-05
  18:08:17", "2024-04-09 10:32:38" (3694 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{status}{%
\section{status}\label{status}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "IP Address". The
  variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{ip_address}{%
\section{ip\_address}\label{ip_address}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2904 \\
Mode & ``103.25.249.240'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-4-ip-address-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "101.2.163.146", "101.2.164.46", "101.2.164.57", "101.2.164.59",
  "101.2.166.50", \ldots, "59.153.17.87", "59.153.202.26",
  "85.170.119.43", "86.99.126.26", "98.42.228.175" (2873 values
  omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{progress}{%
\section{progress}\label{progress}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 14 \\
Mode & ``100'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-5-progress-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{duration_in_seconds}{%
\section{duration\_in\_seconds}\label{duration_in_seconds}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 923 \\
Mode & ``244'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-6-duration-in-seconds-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations: "100",
  "1006", "1009", "101", "1010", \ldots, "988", "991", "993", "997",
  "998" (640 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{finished}{%
\section{finished}\label{finished}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``True'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-7-finished-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recorded_date}{%
\section{recorded\_date}\label{recorded_date}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3711 \\
Mode & ``2024-03-25 21:56:27'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-8-recorded-date-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "2024-03-18 14:16:55", "2024-03-25 20:30:25", "2024-03-25 20:30:55",
  "2024-03-25 20:36:22", "2024-03-25 20:36:35", \ldots, "2024-04-09
  10:26:23", "2024-04-09 10:32:39", "2024-04-09 12:05:00", "2024-04-09
  16:46:59", "2024-04-09 20:50:14" (3701 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{response_id}{%
\section{response\_id}\label{response_id}}

\begin{itemize}
\tightlist
\item
  The variable is a key (distinct values for each observation).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_last_name}{%
\section{recipient\_last\_name}\label{recipient_last_name}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_first_name}{%
\section{recipient\_first\_name}\label{recipient_first_name}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_email}{%
\section{recipient\_email}\label{recipient_email}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{external_reference}{%
\section{external\_reference}\label{external_reference}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{location_latitude}{%
\section{location\_latitude}\label{location_latitude}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1074 (28.83 \%) \\
Number of unique values & 134 \\
Median & 23.73 \\
1st and 3rd quartiles & 23.7; 23.87 \\
Min. and max. & 1.31; 53.45 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-14-location-latitude-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "1.31",
  "3.14", "21.42", "21.48", "22.22", \ldots, "37.38", "37.75", "43.63",
  "48.83", "53.45" (44 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{location_longitude}{%
\section{location\_longitude}\label{location_longitude}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1074 (28.83 \%) \\
Number of unique values & 133 \\
Median & 90.41 \\
1st and 3rd quartiles & 90.37; 90.43 \\
Min. and max. & -122.02; 103.68 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-15-location-longitude-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "-122.02", "-97.82", "-79.37", "-2.32", "2.41", \ldots, "91.87",
  "92.17", "92.23", "101.69", "103.68" (94 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{distribution_channel}{%
\section{distribution\_channel}\label{distribution_channel}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "anonymous". The
  variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{user_language}{%
\section{user\_language}\label{user_language}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``BN'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-17-user-language-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_browser}{%
\section{meta\_info\_browser}\label{meta_info_browser}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 10 \\
Mode & ``Chrome'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-18-meta-info-browser-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "Chrome
  iPhone", "Firefox iPhone", "Safari", "Safari iPad", "UCBrowser".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_version}{%
\section{meta\_info\_version}\label{meta_info_version}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 125 \\
Mode & ``122.0.6261.136'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-19-meta-info-version-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "100.0.4896.58", "102.0.5005.125", "102.0.5005.78", "104.0.5112.97",
  "105.0.5195.79", \ldots, "95.0.0.0", "96.0.4664.104", "97.0.4692.87",
  "97.0.4692.98", "98.0.4758.101" (83 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_operating_system}{%
\section{meta\_info\_operating\_system}\label{meta_info_operating_system}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 24 \\
Mode & ``Android 13'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-20-meta-info-operating-system-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "Android 5.0.2", "Android 7.1.2", "iPad", "Linux x86\_64",
  "Macintosh", "Windows NT 6.1", "Windows NT 6.3".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_resolution}{%
\section{meta\_info\_resolution}\label{meta_info_resolution}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 226 \\
Mode & ``360x800'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-21-meta-info-resolution-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "1024x640", "1024x768", "1093x615", "1098x618", "1280x1024", \ldots,
  "820x1180", "834x1194", "851x393", "873x393", "942x424" (153 values
  omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_agreed}{%
\section{consent\_agreed}\label{consent_agreed}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "I agree to
  participate". The variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_age}{%
\section{consent\_age}\label{consent_age}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "Yes". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_cellphone}{%
\section{consent\_cellphone}\label{consent_cellphone}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "Yes". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{gps_permission}{%
\section{gps\_permission}\label{gps_permission}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 83 (2.23 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-25-gps-permission-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{household_move}{%
\section{household\_move}\label{household_move}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 517 (13.88 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-26-household-move-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_year}{%
\section{flood\_year}\label{flood_year}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 567 (15.22 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-27-flood-year-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{property_loss}{%
\section{property\_loss}\label{property_loss}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2624 (70.44 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-28-property-loss-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{housing_damage}{%
\section{housing\_damage}\label{housing_damage}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2634 (70.71 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-29-housing-damage-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{stay_residence}{%
\section{stay\_residence}\label{stay_residence}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2628 (70.55 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-30-stay-residence-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_close}{%
\section{flood\_close}\label{flood_close}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1725 (46.31 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-31-flood-close-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_prepared}{%
\section{flood\_prepared}\label{flood_prepared}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 859 (23.06 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-32-flood-prepared-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{housing_safe}{%
\section{housing\_safe}\label{housing_safe}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 880 (23.62 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-33-housing-safe-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{climate_problem}{%
\section{climate\_problem}\label{climate_problem}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 886 (23.79 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-34-climate-problem-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{trust_government}{%
\section{trust\_government}\label{trust_government}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 868 (23.3 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-35-trust-government-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{enough_eat}{%
\section{enough\_eat}\label{enough_eat}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 850 (22.82 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-36-enough-eat-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{move_rural_urban}{%
\section{move\_rural\_urban}\label{move_rural_urban}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 871 (23.38 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-37-move-rural-urban-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{contact_authority}{%
\section{contact\_authority}\label{contact_authority}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 893 (23.97 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-38-contact-authority-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_gender}{%
\section{demo\_gender}\label{demo_gender}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 937 (25.15 \%) \\
Number of unique values & 3 \\
Mode & ``Male'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-39-demo-gender-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_age}{%
\section{demo\_age}\label{demo_age}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 960 (25.77 \%) \\
Number of unique values & 232 \\
Mode & ``26'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-40-demo-age-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "01.01.1970", "01/01/1978 ইং", "01822847824", "01870227288", "021",
  \ldots, "আঁট ।", "ও৭", "চল্লিশ বছর", "তেইশ", "প্রায় ৩১" (139 values
  omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_income}{%
\section{demo\_income}\label{demo_income}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1002 (26.9 \%) \\
Number of unique values & 677 \\
Mode & ``10000'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-41-demo-income-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "-", "8".
\item
  Note that the following levels have at most five observations: "-",
  "-10000", ",15000", "?", "'-১০০০০", \ldots, "স্টুডেন্ট কমি", "স্টুডেন্ট
  বেকার", "হয় নাই", "হাঁ", "হিসাব নাই" (593 values omitted).
\item
  Note that there might be case problems with the following levels:
  "6500tk", "6500TK", "no", "No".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone1_try1}{%
\section{comp\_phone1\_try1}\label{comp_phone1_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1231 (33.05 \%) \\
Number of unique values & 2381 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-42-comp-phone1-try1-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "Na".
\item
  Note that the following levels have at most five observations:
  ",+8801834243469", "`+৮৮ ০১৭১২০২২৫২২", "'+880 1643-153421 in",
  "`+৮৮০১৬০৪৩১০৫৬৫", "'+৮৮০১৬০৫২২৮৩২২", \ldots, "প্রয়োজন হবে না।", "লাগবে
  না", "হা", "হে", "হ্যাঁ" (2368 values omitted).
\item
  Note that there might be case problems with the following levels:
  "no", "No".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone1_try2}{%
\section{comp\_phone1\_try2}\label{comp_phone1_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1265 (33.96 \%) \\
Number of unique values & 2352 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-43-comp-phone1-try2-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "Na".
\item
  Note that the following levels have at most five observations:
  "-8801737670961", "`+৮৮ ০১৭১২০২৩৫২২", "'+৮৮০১৬০৪৩১০৫৬৫",
  "`+৮৮০১৬০৫২২৮৩২২", "'+৮৮০১৬৭৬৪৩৫৮৬৮", \ldots, "না", "পারে", "মোবাইল
  ফোনের টাকা পেতে চাই না", "লাগবে না", "হে" (2340 values omitted).
\item
  Note that there might be case problems with the following levels:
  "no", "No".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone2_try1}{%
\section{comp\_phone2\_try1}\label{comp_phone2_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 3556 (95.46 \%) \\
Number of unique values & 167 \\
Mode & ``01778346805'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-44-comp-phone2-try1-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "`+৮৮০১৭৪১৩৮১৩৭৩", "'+৮৮০১৯৩৩৮৪৩৪৬৪", "+08801610264888", "+880
  1515698708", "+8801303392056", \ldots, "না", "বাংলাদেশ গ্রামীণফোন",
  "বুঝতে পারিনি", "মোবাইলে টাকার বিনিময়ে নয়, গবেষণার প্রয়োজনে উওর দিয়েছি",
  "হে" (157 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone2_try2}{%
\section{comp\_phone2\_try2}\label{comp_phone2_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2778}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 3566 (95.73 \%) \\
Number of unique values & 159 \\
Mode & ``'+৮৮০১৭৪১৩৮১৩৭৩'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-45-comp-phone2-try2-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "'+৮৮০১৭৪১৩৮১৩৭৩", "+08801610264888", "+880 1515698708",
  "+8801303392056", "+8801316400051", \ldots, "Sfbvf", "Sssss", "চাইনা",
  "না", "বাড়িতে পেতে চায়" (149 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone3_try1}{%
\section{comp\_phone3\_try1}\label{comp_phone3_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 3702 (99.38 \%) \\
Number of unique values & 22 \\
Mode & ``গ্রামীনে'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-46-comp-phone3-try1-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "+8801311739785", "+8801704657961", "+8801711533890",
  "+8801723745081", "+8801740953468", \ldots, "০১৯৩৩৮৪৩৪৬৪",
  "01985371025", "088.01753044851", "৮৮০১৭১২১০৮৬০৬", "গ্রামীনে" (12
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone3_try2}{%
\section{comp\_phone3\_try2}\label{comp_phone3_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 3701 (99.36 \%) \\
Number of unique values & 23 \\
Mode & ``01763705040'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-47-comp-phone3-try2-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "+8801311739785", "+8801704657961", "+8801711533890",
  "+8801740953468", "01334032604", \ldots, "A", "gp", "Sssss", "হা",
  "হে" (13 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_lat}{%
\section{geo\_lat}\label{geo_lat}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2534 (68.03 \%) \\
Number of unique values & 1158 \\
Mode & ``23.4457891'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-48-geo-lat-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations:
  "-7.8351606", "19.0759837", "20.8720694", "20.9700061", "21.4215534",
  \ldots, "26.3292006", "26.3367685", "3.129616050618498", "33.16335",
  "37.3457116" (1148 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_lng}{%
\section{geo\_lng}\label{geo_lng}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2534 (68.03 \%) \\
Number of unique values & 1158 \\
Mode & ``89.5139265'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-49-geo-lng-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations:
  "-122.0018193", "-96.72518", "101.67602495785316", "112.3778317",
  "39.2073156", \ldots, "92.1777242", "92.2481167", "92.2986433",
  "92.3696622", "92.3780385" (1148 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{q_url}{%
\section{q\_url}\label{q_url}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.0836}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.9164}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3516 \\
Mode &
``\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Dhaka+\%28first+half\%29\&gender=Male\&age=18\&fbclid=IwAR1SbBIa5z1Eqbv6L305z3PLNdTHfCHmLuS3eCK2BreN30Q1pc10pmwgPN8_aem_AX_qu9Ua3-jNJxdVZg2D0FBHexB-oNhml1OOEsqYKywxMfAAq03SwGFcmThb1YiSfiRRa5jIaZ3og_npGV5z1EHI}'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-50-q-url-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?fbclid=IwAR0__8S2iaKxXCvV6q03JWLMVdHZZFLPeURKHbogwzVSyDrSRPhw5HZmS9Y/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?fbclid=IwAR03_k8p7Q7Hfxg5_v6M6mayYdp-6tqR_iFVe4RDOpAbG3ybcldY3Ll-Rdc/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?fbclid=IwAR0DBarq73fNQ3oROoDNvxUez_6dNYCsApTBrjQPotTHRK4fn2-OwCHrL5M_aem_AW4vR88vt8VqpwZ6AYKQc8ArM8G8MsjEdEeH4mKUlB9ZLCvVyywBqmoC4sXtpKU8fUaDoMy-xAixubckdKXLh6v3\&Q_Language=BN®ion=Sylhet\&gender=Male\&age=18/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?fbclid=IwAR0DjF3PqPA60Pa7GybUdDMT9nQW4-I0WOVgjmgGqh_dA-6_hLVhnM4mJZg/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?fbclid=IwAR0eRIOcVjaRl_oxY0DKDMijVr_OVzw2CeQCtMF0hOaen-STXVM3MeM6pfo/}``,
  \ldots,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Sylhet\&gender=Male\&age=50\&fbclid=IwAR3rjT6Yi4azKxK0jl6MDOXG2mA-nfXsruOf_Rp_j9ObGG8T7UQj7pyWzkA_aem_AectU-3l3Jzo4tNYh_328mqUfJZPqUrfg30L9E_6-oiCFQ7ZOZfY13gXnrYj1lEP8QPOlWsmhI9SfY4qRda39iKc/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Sylhet\&gender=Male\&age=50\&fbclid=IwAR3rLoGBpoe_xxPyKzoRdAU4EvCbn-UrX6Cd49aISE6e-lGJKy2vXPecpno_aem_AQL-clGp2aAYz8AEFXsed-Z1pyxY27k7Tc_I8pceCoXQCEPU5PfvKZ2-gMY47iAcm0jZGIwwvozDWLHziqGl3Zpc/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Sylhet\&gender=Male\&age=50\&fbclid=IwAR3VeAm8L9LJw81mU693uavAHumUuDtt0KwAMkTrOvt7XPB-ZS9xHf-G2gw_aem_AU314wYxv6G6F528qGeOnDNGxIr0VAOcJbtL31xo3q1fFA2RJ2CZc36dERVekFUKzjwVHpPngwuUy-dTSUy8Uqpk/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Sylhet\&gender=Male\&age=50\&fbclid=IwAR3wCEvt2HC1K32JEo-Hf0f7CNOjZ7OG68HNhHYYJJNgjGgk96Bj3_l4xEA/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_1N3JWXFRMjZdDls?Q_Language=BN®ion=Sylhet\&gender=Male\&age=50\&fbclid=IwAR3XZZEzcl0y8dEHpFIDJchu2s5yvOY3-2DdVEQ9OHE0jv7mG8AtdLm-edA_aem_AQLq9-A1QmCEYimyQSZZ03O_XoFgoNdtSzGfIdn2j-A3W5l1fZ4JMOnMcRciapDOytY6O3oKk-3_8YoHZhPGTNxM/}''
  (3500 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{q_language}{%
\section{q\_language}\label{q_language}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``BN'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-51-q-language-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{gender}{%
\section{gender}\label{gender}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 117 (3.14 \%) \\
Number of unique values & 2 \\
Mode & ``Male'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-52-gender-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{region}{%
\section{region}\label{region}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3194}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 117 (3.14 \%) \\
Number of unique values & 10 \\
Mode & ``Dhaka (first half)'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-53-region-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{age}{%
\section{age}\label{age}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 117 (3.14 \%) \\
Number of unique values & 3 \\
Mode & ``18'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-54-age-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_capability}{%
\section{geo\_capability}\label{geo_capability}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_status}{%
\section{geo\_status}\label{geo_status}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 593 (15.92 \%) \\
Number of unique values & 3 \\
Mode & ``-1'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-56-geo-status-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_error}{%
\section{geo\_error}\label{geo_error}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "error". The variable
  contains 56.64 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{country}{%
\section{country}\label{country}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{no_surverys_submitted}{%
\section{no\_surverys\_submitted}\label{no_surverys_submitted}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & integer \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 12 \\
Median & 1 \\
1st and 3rd quartiles & 1; 2 \\
Min. and max. & 1; 22 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_bgd_data_files/figure-latex/Var-59-no-surverys-submitted-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: Sofia Ingersoll (username: \texttt{sofiaingersoll}).
\item
  Report creation time: Sun Apr 21 2024 19:01:12
\item
  Report was run from directory:
  \texttt{/Users/sofiaingersoll/2035/Adaptation\_Observatory}
\item
  dataMaid v1.4.1 {[}Pkg: 2021-10-08 from CRAN (R 4.3.0){]}
\item
  R version 4.3.2 (2023-10-31).
\item
  Platform: aarch64-apple-darwin20 (64-bit)(America/Los\_Angeles).
\item
  Function call: \texttt{makeDataReport(data\ =\ bgd\_data)}
\end{itemize}

\end{document}
