% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{report}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={India Adaptation Observation Survey Responses, Retrieval Date 15 April 2024.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{India Adaptation Observation Survey Responses, Retrieval Date 15
April 2024.}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2024-04-21 23:28:58.888338}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\chapter{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3472}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Number of observations & 1227 \\
Number of variables & 60 \\
\end{longtable}

\hypertarget{checks-performed}{%
\subsection{Checks performed}\label{checks-performed}}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.3649}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0811}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1149}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0676}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
character
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
haven labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
numeric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
integer
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
logical
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Date
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Identify miscoded missing values & \(\times\) & \(\times\) & \(\times\)
& \(\times\) & \(\times\) & \(\times\) & & \(\times\) \\
Identify prefixed and suffixed whitespace & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify levels with \textless{} 6 obs. & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify case issues & \(\times\) & \(\times\) & \(\times\) & \(\times\)
& & & & \\
Identify misclassified numeric or integer variables & \(\times\) &
\(\times\) & \(\times\) & \(\times\) & & & & \\
Identify outliers & & & & & \(\times\) & \(\times\) & & \(\times\) \\
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\hypertarget{summary-table}{%
\chapter{Summary table}\label{summary-table}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.3148}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1574}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2130}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1481}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Variable class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\# unique values
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Missing observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Any problems?
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\protect\hyperlink{start_date}{start\_date} & character & 1227 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{end_date}{end\_date} & character & 1225 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{status}{status} & character & 1 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{ip_address}{ip\_address} & character & 1207 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{progress}{progress} & character & 3 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{duration_in_seconds}{duration\_in\_seconds} &
character & 512 & 0.00 \% & \(\times\) \\
\protect\hyperlink{finished}{finished} & character & 2 & 0.00 \% & \\
\protect\hyperlink{recorded_date}{recorded\_date} & character & 1225 &
0.00 \% & \(\times\) \\
\protect\hyperlink{response_id}{response\_id} & character & 1227 & 0.00
\% & \(\times\) \\
\protect\hyperlink{recipient_last_name}{recipient\_last\_name} &
character & 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{recipient_first_name}{recipient\_first\_name} &
character & 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{recipient_email}{recipient\_email} & character & 1 &
100.00 \% & \(\times\) \\
\protect\hyperlink{external_reference}{external\_reference} & character
& 1 & 100.00 \% & \(\times\) \\
\protect\hyperlink{location_latitude}{location\_latitude} & numeric & 72
& 1.22 \% & \(\times\) \\
\protect\hyperlink{location_longitude}{location\_longitude} & numeric &
72 & 1.22 \% & \(\times\) \\
\protect\hyperlink{distribution_channel}{distribution\_channel} &
character & 1 & 0.00 \% & \(\times\) \\
\protect\hyperlink{user_language}{user\_language} & character & 9 & 0.00
\% & \(\times\) \\
\protect\hyperlink{meta_info_browser}{meta\_info\_browser} & character &
4 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_version}{meta\_info\_version} & character &
77 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_operating_system}{meta\_info\_operating\_system}
& character & 20 & 0.00 \% & \(\times\) \\
\protect\hyperlink{meta_info_resolution}{meta\_info\_resolution} &
character & 133 & 0.00 \% & \(\times\) \\
\protect\hyperlink{consent_agreed}{consent\_agreed} & character & 1 &
0.00 \% & \(\times\) \\
\protect\hyperlink{consent_age}{consent\_age} & character & 1 & 0.00 \%
& \(\times\) \\
\protect\hyperlink{consent_cellphone}{consent\_cellphone} & character &
1 & 0.00 \% & \(\times\) \\
\protect\hyperlink{gps_permission}{gps\_permission} & character & 1 &
0.00 \% & \(\times\) \\
\protect\hyperlink{household_move}{household\_move} & character & 3 &
0.08 \% & \\
\protect\hyperlink{flood_year}{flood\_year} & character & 3 & 0.08 \%
& \\
\protect\hyperlink{property_loss}{property\_loss} & character & 3 &
71.88 \% & \\
\protect\hyperlink{housing_damage}{housing\_damage} & character & 3 &
71.88 \% & \\
\protect\hyperlink{stay_residence}{stay\_residence} & character & 3 &
72.05 \% & \\
\protect\hyperlink{flood_close}{flood\_close} & character & 3 & 28.20 \%
& \\
\protect\hyperlink{flood_prepared}{flood\_prepared} & character & 5 &
0.00 \% & \\
\protect\hyperlink{housing_safe}{housing\_safe} & character & 6 & 0.24
\% & \\
\protect\hyperlink{climate_problem}{climate\_problem} & character & 6 &
0.41 \% & \\
\protect\hyperlink{trust_government}{trust\_government} & character & 6
& 0.16 \% & \\
\protect\hyperlink{enough_eat}{enough\_eat} & character & 2 & 0.00 \%
& \\
\protect\hyperlink{move_rural_urban}{move\_rural\_urban} & character & 2
& 0.00 \% & \\
\protect\hyperlink{contact_authority}{contact\_authority} & character &
3 & 0.16 \% & \\
\protect\hyperlink{demo_gender}{demo\_gender} & character & 4 & 0.08 \%
& \(\times\) \\
\protect\hyperlink{demo_age}{demo\_age} & character & 101 & 0.08 \% &
\(\times\) \\
\protect\hyperlink{demo_income}{demo\_income} & character & 302 & 2.61
\% & \(\times\) \\
\protect\hyperlink{comp_phone1_try1}{comp\_phone1\_try1} & character &
1201 & 0.00 \% & \(\times\) \\
\protect\hyperlink{comp_phone1_try2}{comp\_phone1\_try2} & character &
1202 & 0.00 \% & \(\times\) \\
\protect\hyperlink{comp_phone2_try1}{comp\_phone2\_try1} & character &
87 & 92.99 \% & \(\times\) \\
\protect\hyperlink{comp_phone2_try2}{comp\_phone2\_try2} & character &
90 & 92.75 \% & \(\times\) \\
\protect\hyperlink{comp_phone3_try1}{comp\_phone3\_try1} & character &
16 & 98.78 \% & \(\times\) \\
\protect\hyperlink{comp_phone3_try2}{comp\_phone3\_try2} & character &
16 & 98.78 \% & \(\times\) \\
\protect\hyperlink{geo_lat}{geo\_lat} & character & 516 & 57.70 \% &
\(\times\) \\
\protect\hyperlink{geo_lng}{geo\_lng} & character & 515 & 57.70 \% &
\(\times\) \\
\protect\hyperlink{q_url}{q\_url} & character & 1217 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{q_language}{q\_language} & character & 9 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{gender}{gender} & character & 3 & 0.57 \% & \\
\protect\hyperlink{region}{region} & character & 12 & 0.57 \% &
\(\times\) \\
\protect\hyperlink{age}{age} & character & 4 & 0.57 \% & \\
\protect\hyperlink{geo_capability}{geo\_capability} & character & 1 &
100.00 \% & \(\times\) \\
\protect\hyperlink{geo_status}{geo\_status} & character & 3 & 0.00 \%
& \\
\protect\hyperlink{geo_error}{geo\_error} & character & 2 & 50.86 \% &
\(\times\) \\
\protect\hyperlink{country}{country} & character & 1 & 100.00 \% &
\(\times\) \\
\protect\hyperlink{no_surverys_submitted}{no\_surverys\_submitted} &
integer & 2 & 0.00 \% & \\
\protect\hyperlink{income_brackets}{income\_brackets} & character & 5 &
2.61 \% & \\
\end{longtable}

\hypertarget{variable-list}{%
\chapter{Variable list}\label{variable-list}}

\hypertarget{start_date}{%
\section{start\_date}\label{start_date}}

\begin{itemize}
\tightlist
\item
  The variable is a key (distinct values for each observation).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{end_date}{%
\section{end\_date}\label{end_date}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1225 \\
Mode & ``2024-03-28 04:51:05'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-2-end-date-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "2024-03-26 19:32:39", "2024-03-26 19:38:38", "2024-03-26 19:40:22",
  "2024-03-26 19:40:55", "2024-03-26 19:41:11", \ldots, "2024-04-01
  03:13:28", "2024-04-01 07:53:47", "2024-04-02 08:30:41", "2024-04-02
  16:05:33", "2024-04-06 07:25:16" (1215 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{status}{%
\section{status}\label{status}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "IP Address". The
  variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{ip_address}{%
\section{ip\_address}\label{ip_address}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1207 \\
Mode & ``103.85.10.250'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-4-ip-address-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "1.187.142.50", "1.187.180.12", "1.38.104.25", "1.38.105.233",
  "1.38.105.28", \ldots, "59.95.172.63", "59.95.3.25", "60.243.84.200",
  "60.254.0.185", "61.1.138.225" (1197 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{progress}{%
\section{progress}\label{progress}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3 \\
Mode & ``100'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-5-progress-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "94".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{duration_in_seconds}{%
\section{duration\_in\_seconds}\label{duration_in_seconds}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 512 \\
Mode & ``208'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-6-duration-in-seconds-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations: "100",
  "1021", "104", "1042", "106", \ldots, "946", "955", "9586", "98",
  "987" (470 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{finished}{%
\section{finished}\label{finished}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``True'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-7-finished-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recorded_date}{%
\section{recorded\_date}\label{recorded_date}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1225 \\
Mode & ``2024-03-27 01:13:06'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-8-recorded-date-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "2024-03-26 19:32:40", "2024-03-26 19:38:39", "2024-03-26 19:40:23",
  "2024-03-26 19:40:56", "2024-03-26 19:41:12", \ldots, "2024-04-06
  07:52:11", "2024-04-06 10:24:31", "2024-04-07 01:06:48", "2024-04-07
  07:58:09", "2024-04-07 08:38:30" (1215 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{response_id}{%
\section{response\_id}\label{response_id}}

\begin{itemize}
\tightlist
\item
  The variable is a key (distinct values for each observation).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_last_name}{%
\section{recipient\_last\_name}\label{recipient_last_name}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_first_name}{%
\section{recipient\_first\_name}\label{recipient_first_name}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{recipient_email}{%
\section{recipient\_email}\label{recipient_email}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{external_reference}{%
\section{external\_reference}\label{external_reference}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{location_latitude}{%
\section{location\_latitude}\label{location_latitude}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 15 (1.22 \%) \\
Number of unique values & 71 \\
Median & 22.52 \\
1st and 3rd quartiles & 14.08; 23.03 \\
Min. and max. & 8.76; 28.65 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-14-location-latitude-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "23.59", "23.68", "23.73", "23.73", "23.92", \ldots, "26.88", "26.95",
  "28.61", "28.65", "28.65" (9 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{location_longitude}{%
\section{location\_longitude}\label{location_longitude}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 15 (1.22 \%) \\
Number of unique values & 71 \\
Median & 73.07 \\
1st and 3rd quartiles & 72.59; 80.22 \\
Min. and max. & 70.06; 93.94 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-15-location-longitude-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "70.06", "70.46", "70.79", "70.84", "71.21", "71.81", "72.19".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{distribution_channel}{%
\section{distribution\_channel}\label{distribution_channel}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "anonymous". The
  variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{user_language}{%
\section{user\_language}\label{user_language}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 9 \\
Mode & ``EN'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-17-user-language-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "MAL".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_browser}{%
\section{meta\_info\_browser}\label{meta_info_browser}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 4 \\
Mode & ``Chrome'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-18-meta-info-browser-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "Edge",
  "Safari".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_version}{%
\section{meta\_info\_version}\label{meta_info_version}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 77 \\
Mode & ``122.0.6261.119'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-19-meta-info-version-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "103.0.5060.129", "103.0.5060.71", "106.0.0.0", "106.0.5249.126",
  "107.0.5304.141", \ldots, "92.0.4515.131", "93.0.4577.62",
  "96.0.4664.104", "96.0.4664.45", "99.0.4844.73" (48 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_operating_system}{%
\section{meta\_info\_operating\_system}\label{meta_info_operating_system}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 20 \\
Mode & ``Android 13'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-20-meta-info-operating-system-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "581020724", "Android 6.0", "Android 7.0", "Android 7.1.1", "Android
  7.1.2", \ldots, "m13", "m33x", "Macintosh", "r0q", "y2q" (1 values
  omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{meta_info_resolution}{%
\section{meta\_info\_resolution}\label{meta_info_resolution}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 133 \\
Mode & ``360x800'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-21-meta-info-resolution-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "1280x1024", "1280x720", "1366x768", "1440x900", "1446x704", \ldots,
  "686x1143", "780x360", "800x1280", "873x393", "876x393" (85 values
  omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_agreed}{%
\section{consent\_agreed}\label{consent_agreed}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "I agree to
  participate". The variable contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_age}{%
\section{consent\_age}\label{consent_age}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "Yes". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{consent_cellphone}{%
\section{consent\_cellphone}\label{consent_cellphone}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "Yes". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{gps_permission}{%
\section{gps\_permission}\label{gps_permission}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "Yes". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{household_move}{%
\section{household\_move}\label{household_move}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1 (0.08 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-26-household-move-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_year}{%
\section{flood\_year}\label{flood_year}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1 (0.08 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-27-flood-year-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{property_loss}{%
\section{property\_loss}\label{property_loss}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 882 (71.88 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-28-property-loss-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{housing_damage}{%
\section{housing\_damage}\label{housing_damage}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 882 (71.88 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-29-housing-damage-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{stay_residence}{%
\section{stay\_residence}\label{stay_residence}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 884 (72.05 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-30-stay-residence-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_close}{%
\section{flood\_close}\label{flood_close}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 346 (28.2 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-31-flood-close-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{flood_prepared}{%
\section{flood\_prepared}\label{flood_prepared}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-32-flood-prepared-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{housing_safe}{%
\section{housing\_safe}\label{housing_safe}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 3 (0.24 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-33-housing-safe-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{climate_problem}{%
\section{climate\_problem}\label{climate_problem}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 5 (0.41 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-34-climate-problem-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{trust_government}{%
\section{trust\_government}\label{trust_government}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2 (0.16 \%) \\
Number of unique values & 5 \\
Mode & ``Strongly agree'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-35-trust-government-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{enough_eat}{%
\section{enough\_eat}\label{enough_eat}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-36-enough-eat-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{move_rural_urban}{%
\section{move\_rural\_urban}\label{move_rural_urban}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``Yes'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-37-move-rural-urban-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{contact_authority}{%
\section{contact\_authority}\label{contact_authority}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 2 (0.16 \%) \\
Number of unique values & 2 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-38-contact-authority-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_gender}{%
\section{demo\_gender}\label{demo_gender}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1 (0.08 \%) \\
Number of unique values & 3 \\
Mode & ``Male'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-39-demo-gender-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "Non-binary/other".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_age}{%
\section{demo\_age}\label{demo_age}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1 (0.08 \%) \\
Number of unique values & 100 \\
Mode & ``30'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-40-demo-age-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: ",28",
  "+919725033808", "03/05/1969", "17", "19-05-1961", \ldots, "76109",
  "77", "7752", "78", "Sixty four" (47 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{demo_income}{%
\section{demo\_income}\label{demo_income}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 32 (2.61 \%) \\
Number of unique values & 301 \\
Mode & ``10000'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-41-demo-income-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "Na".
\item
  Note that the following levels have at most five observations: ",
  29000/-", "+919725033808", "\$0", "\$120", "\$150", \ldots, "জানিনা",
  "না", "இல்லை", "வருமானம் ஏதும் இல்லை", "లెదు" (254 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone1_try1}{%
\section{comp\_phone1\_try1}\label{comp_phone1_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1201 \\
Mode & ``No'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-42-comp-phone1-try1-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "*91-9989988008", "++91 8779619188", "+91 70059 75018", "+91
  7016591708", "+91 7046753102", \ldots, "9998460260", "9999988888", "I
  pass", "K", "Thanks for including our region in your study prof!"
  (1190 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone1_try2}{%
\section{comp\_phone1\_try2}\label{comp_phone1_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1202 \\
Mode & ``918983057930'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-43-comp-phone1-try2-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  ",8008178324", ",9841404049", "+91 70059 75018", "+91 7016591708",
  "+91 7046753102", \ldots, "I pass", "K", "No", "Thanks for including
  our region in your study prof!", "હા" (1192 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone2_try1}{%
\section{comp\_phone2\_try1}\label{comp_phone2_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1141 (92.99 \%) \\
Number of unique values & 86 \\
Mode & ``+91 8758688414'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-44-comp-phone2-try1-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "+91
  8758688414", "+91 8780247663", "+916374213067", "+917005746923",
  "+919440517116", \ldots, "9913194391", "9971573145", "9974483308",
  "9987759911", "No" (76 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone2_try2}{%
\section{comp\_phone2\_try2}\label{comp_phone2_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1138 (92.75 \%) \\
Number of unique values & 89 \\
Mode & ``+91 8758688414'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-45-comp-phone2-try2-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "+91
  8758688414", "+916374213067", "+917005746923", "+918780247663",
  "+919440517116", \ldots, "9971573145", "9974483308", "9987759911",
  "No", "હા" (79 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone3_try1}{%
\section{comp\_phone3\_try1}\label{comp_phone3_try1}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1212 (98.78 \%) \\
Number of unique values & 15 \\
Mode & ``6355300098'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-46-comp-phone3-try1-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "6355300098", "7016461149", "76394 65354", "8144956601", "8328961903",
  \ldots, "918780247663", "919000271573", "919392434213",
  "919726317496", "9503546721" (5 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comp_phone3_try2}{%
\section{comp\_phone3\_try2}\label{comp_phone3_try2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 1212 (98.78 \%) \\
Number of unique values & 15 \\
Mode & ``7016461149'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-47-comp-phone3-try2-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "7016461149", "76394 65354", "7907621877", "8328961903", "9049110998",
  \ldots, "919392434213", "919726317496", "919879774309", "9503546721",
  "હા" (5 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_lat}{%
\section{geo\_lat}\label{geo_lat}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 708 (57.7 \%) \\
Number of unique values & 515 \\
Mode & ``18.9502044'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-48-geo-lat-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations:
  "10.0006676", "10.349449", "10.4866279", "10.6678316", "10.7966026",
  \ldots, "9.000800129999996", "9.0838393", "9.503249", "9.7219761",
  "9.9997732" (505 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_lng}{%
\section{geo\_lng}\label{geo_lng}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 708 (57.7 \%) \\
Number of unique values & 514 \\
Mode & ``70.8146097'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-49-geo-lng-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations:
  "68.9638325", "69.3546141", "69.3639259", "69.4886958", "69.5681388",
  \ldots, "91.3003905", "91.3068005", "91.4696038", "91.8128906",
  "92.1941493" (504 values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{q_url}{%
\section{q\_url}\label{q_url}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1844}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.8156}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1217 \\
Mode &
``\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=Andhra+Pradesh\&gender=Male\&age=18}'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-50-q-url-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?fbclid=IwAR0Dn9I2QuL82a6Q88oood3pApasbwGvVm_h9lZAzUx6mAd8FzcUE9k7Zog/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?fbclid=IwAR1pfHZ6-iRocZ2bPbIUOZASbleOVmE15zSOPltHSsbumTyNCc4AqbLahxY/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?fbclid=IwAR1Tq8ECp3-Qomlp_4JDRXWtdhHFsVyy2kCvYyrNuEW7WJN5gO3ba-46NEg/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?fbclid=IwAR209V33_AwGqrx3a5XlQ2b7KCPLbnmnvwWS2XxeRpjVJjADXEsmZDF9MSM_aem_AX9AHZyEVrfsfsBfH_48n3J3VQFHWXhPZVpCGCA1bLG5d3xj4nUc_qJ1bHBDn4eM6khCVM-OvAxBG3J70uNlLNUo/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?fbclid=IwAR2IqcKrHpvW5O8epjHpHUugkzOSsewRQJ9xAZ_EsVofVBQEi8c3CeYUeNM/}``,
  \ldots,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=West+Bengal++\%28second+half\%29\&gender=Male\&age=50\&fbclid=IwAR057VRmqAIWENBr3UqIrGg9uq5vp7r4_Ste2cGml2HR4OVTSWmcoDHPhkU_aem_AWWm7eR3JOhWPJuKQpSqqkcFgmAH39jIFGvRBV_715aGjaRIX7I8RryOg2Exi22XLCmHGqK4Z8uuy1CM1TlNJtH8/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=West+Bengal++\%28second+half\%29\&gender=Male\&age=50\&fbclid=IwAR1v9oj-ThJwVAOG47VOearNfsp_AGqEYp5eE9raL5DmCnlhyX_96Vp_ELY_aem_AR9Tm-qJCk2kEkWlccnGPl-bFhl_AaEHwDY7ka6wuEQPZFCRGDjrh1gSL-T6bZMxrHnV9j--z1mOLcikZi46z8KJ/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=West+Bengal++\%28second+half\%29\&gender=Male\&age=50\&fbclid=IwAR29-2dAU8DkrFiAtuVTuwQvLEky-VHtNz9P6YJFRogS6Mhf2xgUtwlGAcM_aem_AWBP8WgjWNhg7vpZvXz1z4G_nu4wT9AWeWGyp0wByYD0EPBAEtK3JYS9gSH0ydEJqF_PiAUUnKacSFTrDxY4IU6y/}'',
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=West+Bengal++\%28second+half\%29\&gender=Male\&age=50\&fbclid=IwAR2GFuMY3kzCbhi_OVVgvCII5H60CU7RKkeNE0_zy395mcyoqFESv4P-mWA_aem_AWekHzvxAGrD2VKjZt8YsglSlWPrTrzS8w0eDqpsLH_9208_ozZSK8JaLHxpi5qGoXn61puV_Hb9u_ybyFdB17fw/}``,
  "\url{https://ucsb.co1.qualtrics.com/jfe/form/SV_28ZOxlwZy4635uS?Q_Language=EN®ion=West+Bengal++\%28second+half\%29\&gender=Male\&age=50\&fbclid=PAAaYqzjyEfKWL2JyVZZeGk4dWWMVTG5T3RDiGvaqFAaDQf5Zky3qgI9jD9Dc_aem_AWfydDOV75ZCZ-hsjhtpoey1um9kTsu-L6KWFsbQkaN4s90FDtR1hFR9G2al1Ix3VNVljTkCxyGZELOSRwp86cQA/}''
  (1207 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{q_language}{%
\section{q\_language}\label{q_language}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 9 \\
Mode & ``EN'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-51-q-language-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "MAL".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{gender}{%
\section{gender}\label{gender}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 7 (0.57 \%) \\
Number of unique values & 2 \\
Mode & ``Male'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-52-gender-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{region}{%
\section{region}\label{region}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 7 (0.57 \%) \\
Number of unique values & 11 \\
Mode & ``Gujarāt'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-53-region-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "States\textless10Points".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{age}{%
\section{age}\label{age}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 7 (0.57 \%) \\
Number of unique values & 3 \\
Mode & ``30'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-54-age-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_capability}{%
\section{geo\_capability}\label{geo_capability}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_status}{%
\section{geo\_status}\label{geo_status}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3 \\
Mode & ``-1'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-56-geo-status-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{geo_error}{%
\section{geo\_error}\label{geo_error}}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "error". The variable
  contains 50.86 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{country}{%
\section{country}\label{country}}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{no_surverys_submitted}{%
\section{no\_surverys\_submitted}\label{no_surverys_submitted}}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & integer \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``1'' \\
Reference category & 1 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-59-no-surverys-submitted-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{income_brackets}{%
\section{income\_brackets}\label{income_brackets}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5139}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 32 (2.61 \%) \\
Number of unique values & 4 \\
Mode & ``0\% Tax Rate (Up to Rs. 3,00,000)'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_ind_files/figure-latex/Var-60-income-brackets-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: Sofia Ingersoll (username: \texttt{sofiaingersoll}).
\item
  Report creation time: Sun Apr 21 2024 23:28:59
\item
  Report was run from directory:
  \texttt{/Users/sofiaingersoll/2035/Adaptation\_Observatory/response\_analysis/dataMaid}
\item
  dataMaid v1.4.1 {[}Pkg: 2021-10-08 from CRAN (R 4.3.0){]}
\item
  R version 4.3.2 (2023-10-31).
\item
  Platform: aarch64-apple-darwin20 (64-bit)(America/Los\_Angeles).
\item
  Function call:
  \texttt{makeDataReport(data\ =\ ind,\ output\ =\ "pdf",\ replace\ =\ TRUE,\ reportTitle\ =\ "India\ Adaptation\ Observation\ Survey\ Responses,\ Retrieval\ Date\ 15\ April\ 2024.")}
\end{itemize}

\end{document}
