# Map

## Load & Wrangle Survey Demographic Data

```{r warning = FALSE}
bgd_responses <- read_csv(here("..","data","adapt_observ_survey_responses", "Observatory_Bangladesh_2024_04_11.csv"), show_col_types = FALSE)
  
ind_responses <-read_csv(here("..","data","adapt_observ_survey_responses", "Observatory_India_2024_04_11.csv"), show_col_types = FALSE)


# these lines are grouped by demographics of interest
  # top line relates to personal demographics
bgd_demos <- bgd_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))
 


# these lines are grouped by demographics of interest
  # top line relates to personal demographics
ind_demos <- ind_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))
```
### What's the most number of surveys a single ip address has submitted?
```{r}
# let's check our new column
max(bgd_demos$number_of_surverys_submitted)

max(ind_demos$number_of_surverys_submitted)
```


### Density Distribution of Gender based on Age & Colored by Region (facet wrap by Gender)

also Age vs Demo_Age colored by gender

Werk in progress

## Geospatial Analysis
For anoynmity purposes, it's best these plots don't render with the IP Addresses
```{r}
ind_demo_sf <- ind_demos %>% 
  st_as_sf(coords = c("location_longitude", "location_latitude"), crs = "EPSG:4326")
  
  
tmap_mode('view')

ind_response_map <- tm_shape(ind_demo_sf) +
  tm_basemap(leaflet::providers$Esri.WorldImagery) +
  tm_bubbles(alpha = 0.2,
             fill = 'ip_address',
             col = 'skyblue',) +
  tm_scalebar(position = c('left', 'bottom')) +
  tm_title("Adaptation Observatory Responses, Bangladesh (2024-4-11)")

ind_response_map
```


```{r}
bgd_demo_sf <- bgd_demos %>% 
  
  st_as_sf(coords = c("location_longitude", "location_latitude"), crs = 4326)
  
  
tmap_mode('view')

bgd_response_map <- tm_shape(bgd_demo_sf) +
  tm_basemap(leaflet::providers$Esri.WorldImagery) +
  tm_bubbles(alpha = 0.2,
             fill = 'ip_address',
             col = 'skyblue',) +
  tm_scalebar(position = c('left', 'bottom')) +
  tm_title("Adaptation Observatory Responses, Bangladesh (2024-4-11)")


bgd_response_map
```

