# Tree Map

## Load & Wrangle Survey Demographic Data
```{r warning = FALSE}
library(tidyverse)        # load the tidyverse package to assist with data wrangling & cleaning 
library(treemap)
library(patchwork)        # load the patchwork package to assist in plot composition (displaying multiple data visualizations) 

library(showtext)         # load the showtext to more easily use fonts
library(here)
library(purrr)

bgd_file <- file.path(here("..","data","adapt_observ_survey_responses", "Observatory_Bangladesh_2024_04_15.csv"))
  
ind_file <- file.path(here("..","data","adapt_observ_survey_responses", "Observatory_India_2024_04_15.csv"))

bgd_responses <- read_csv(bgd_file, show_col_types = FALSE)
  
ind_responses <-read_csv(ind_file, show_col_types = FALSE)


bgd_demos <- bgd_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))
 

ind_demos <- ind_responses %>%
  dplyr::select(IPAddress, age, gender, region, LocationLatitude, LocationLongitude, demo_age, demo_gender,
                 # impact of floods
                flood_year, housing_damage, property_loss, contact_authority, flood_close,
                 # socioeconomic factors & resiliency / scarcity 
                stay_residence, flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) %>%
  
  janitor::clean_names() %>%
  
  # Treat NA as a separate category
  mutate(across(where(is.character), ~ifelse(. %in% c(NA, "NA"), "Not Disclosed", .)),
         across(where(is.numeric), ~ifelse(is.na(.), "Not Disclosed", .))) %>% 
  
  mutate(location_longitude = as.numeric(location_longitude),
         location_latitude = as.numeric(location_latitude)) %>%
  # remove incomplete geolocations
  filter(complete.cases(location_latitude, location_longitude)) %>% 
  # Count the occurrences of each IPAddress
  group_by(ip_address) %>%
  mutate(number_of_surverys_submitted = n()) %>%
  ungroup() %>%
  # remove first two rows
  slice(-c(1, 2))

# load function
# Source the .R file containing the function
#source(here("survey_responses/read_n_wrangle_data.R"))

#bgd_demos <-read_n_wrangle_data(bgd_responses)
bgd_demos

#ind_demos <- read_n_wrangle_data(ind_responses)
ind_demos
```
```{r region_gender_age, fig.height=10, fig.width=22}
# Grouping the data by region
grouped_data <- ind_demos %>%
  group_by(region) %>%
  mutate(across(
    .cols = all_of(cols_to_calc),
    .fns = list(
      Yes = ~ mean(. %in% c("Yes", "yes")),
      No = ~ mean(. %in% c("No", "no")),
      `Not Disclosed` = ~ mean(is.na(.) | . == "Not Disclosed")
    ),
    .names = "{.col}_{.fn}"
  )) %>%
  ungroup()

# Now, group by all variables including region
grouped_data <- grouped_data %>%
  group_by(region, gender, demo_gender, age, demo_age, flood_year, housing_damage, property_loss, contact_authority, flood_close, flood_prepared,
           stay_residence, enough_eat, move_rural_urban, demo_income) %>%
  summarise(number_of_surveys_submitted = n()) %>%
  ungroup()

# Define a color palette
library(RColorBrewer)
colors <- brewer.pal(11, 'Set3') # You can choose any color palette from RColorBrewer 
brewer.pal.info

# Create the treemap with the specified color palette
treemap(grouped_data,
        index=c("region", "gender", "age"#, "flood_year"#, "property_loss", "contact_authority", 
               # "flood_close", "stay_residence", "enough_eat", "move_rural_urban", "demo_income
               ),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response Categories: Region, Gender, and Age",
        palette=colors,
        # Increase the font size of the title
        fontsize.title = 20,   
         # Font size for region titles and other labels
        fontsize.labels = c(16, 12), 
        # Set border color to white for better visibility
        border.col = "white",  
        # Align labels to center
        align.labels = list(c("center", "center")),  
        # Adjust overlap for better readability
        overlap.labels = 1,
        # Add a margin (top, right, bottom, left)
        margin = c(20, 20, 20, 20),
        
        fontsize.labels.bg = c(20, 20),  # Font size for background labels
        
         # Set background color of labels to transparent
        fontsize.labels.bg = c(14, 12)  # Font size for background labels
        
        )
```
```{r char_tree fig.height=11, fig.width=25}
# Define a color palette
library(RColorBrewer)
colors <- rev(brewer.pal(11, "Set3")) # Using a qualitative color palette for categorical data

# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, and Age",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )

```
```{r gender_age, fig.height=11, fig.width=25}
# Define a color palette
library(RColorBrewer)
colors <- rev(brewer.pal(11, "Set3")) # Using a qualitative color palette for categorical data

# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region","gender", "demo_gender", "age", "demo_age"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, and Age Demographic Distribution",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
```{r flood_year, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "flood_year"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Flood Year",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```

```{r housing_damage, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "housing_damage"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Housing Damage",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```

```{r property_loss, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "property_loss"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Property Loss",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
                
```{r contact_authorities, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "contact_authority"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Contact Authorities",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
```{r flood_close, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "flood_close"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Flood Close",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
 flood_prepared, housing_safe, enough_eat, move_rural_urban, demo_income, 
                # sentiments 
                climate_problem, trust_government) 
```{r stay_residence, fig.height=11, fig.width=25}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "stay_residence"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Stay Residence",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(27, 20, 18),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
```{r flood_prepared, fig.height=14, fig.width=35}
# Create the treemap with improved labels, layout, and margin
treemap(grouped_data,
        index=c("region", "gender", "age", "flood_prepared"),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response: Region, Gender, Age and Flood Prepared",
        palette=colors,
        fontsize.title = 40,   # Increase the font size of the title
        fontsize.labels = c(30, 25, 20),  # Font size for region titles and other labels
        border.col = "white",  # Set border color to white for better visibility
        align.labels = list(c("center", "center")),  # Align labels to center
        overlap.labels = 0,  # Adjust overlap for better readability
        bg.labels = "transparent",  # Set background color of labels to transparent
        margin = c(20, 20, 20, 20),  # Add a margin (top, right, bottom, left)
        fontsize.labels.bg = c(16, 14),  # Font size for background labels
        border.lwds = 1.5
        )
```
```{r gender_age_demo}
# Create the treemap with the specified color palette

grouped_data
treemap(grouped_data,
        index=c("region", "gender", "demo_gender", "age", "demo_age"#, "flood_year"#, "property_loss", "contact_authority", 
               # "flood_close", "stay_residence", "enough_eat", "move_rural_urban", "demo_income
               ),
        vSize="number_of_surveys_submitted",
        algorithm="squarified",
        title="India Survey Response Categories: Region, Gender, and Age",
        palette=colors,
        # Increase the font size of the title
        fontsize.title = 20,   
         # Font size for region titles and other labels
        fontsize.labels = c(16, 12), 
        # Set border color to white for better visibility
        border.col = "white",  
        # Align labels to center
        align.labels = list(c("center", "center")),  
        # Adjust overlap for better readability
        overlap.labels = 0.5,
        # Add a margin (top, right, bottom, left)
        margin = c(20, 0.02, 0.02, 10),
        
        fontsize.labels.bg = c(20, 20),  # Font size for background labels
        
         # Set background color of labels to transparent
        fontsize.labels.bg = c(14, 12)  # Font size for background labels
        
        )
```

